name       : python-markupsafe
version    : '1.0'
release    : 5
source     :
    - https://github.com/pallets/markupsafe/archive/1.0.tar.gz : dc3938045d9407a73cf9fdd709e2b1defd0588d50ffc85eb0786c095ec846f15
license    : BSD-3-Clause
component  : programming.python
summary    : Implements a XML/HTML/XHTML Markup safe string for Python
description: |
    Implements a XML/HTML/XHTML Markup safe string for Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
