name       : python-markupsafe
version    : 2.1.1
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/M/MarkupSafe/MarkupSafe-2.1.1.tar.gz : 7f91197cc9e48f989d12e4e6fbc46495c446636dfc81b9ccf50bb0ec74b91d4b
homepage   : https://palletsprojects.com/p/markupsafe/
license    : BSD-3-Clause
component  : programming.python
summary    : Implements a XML/HTML/XHTML Markup safe string for Python
description: |
    MarkupSafe implements a text object that escapes characters so it is safe to use in HTML and XML. Characters that have special meanings are replaced so that they display as the actual characters. This mitigates injection attacks, meaning untrusted user input can safely be displayed on a page. Escaping is implemented in C so it is as efficient as possible.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
