name       : python-markupsafe
version    : 1.1.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz : 29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b
license    : BSD-3-Clause
component  : programming.python
summary    : Implements a XML/HTML/XHTML Markup safe string for Python
description: |
    Implements a XML/HTML/XHTML Markup safe string for Python
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
